language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
	- 7.1
	- 7.2

env:
  global:
    - TEST_COMMAND="composer test"

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true PHPUNIT_FLAGS="--coverage-clover build/coverage.xml"

before_install:
	- travis_retry composer self-update

install:
	- travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
	- $TEST_COMMAND

after_success:
	- if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
	- if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi